### PR TITLE
Converted a Figma UI design of product page into web page

### PR DESCRIPTION
**Pull request by heyaadarsh**
I got a design of a product info page on https://uidesigndaily.com/ (the link that you mentioned) and I converted the design into a web page using pure HTML & CSS. I request you to please check it out and merge it to your awesome repo & if you have any suggestions then I am ready to work on it.

### CODE REVIEW

**Comment by SooryaCodes** [comment]
Thank you so much bro for participating ✨️.

**Comment by heyaadarsh** [comment]
> Thank you so much bro for participating ✨️.

It's my pleasure brother! Thanks for merging the PR.

**Comment by heyaadarsh** [comment]
Hi @SooryaCodes 
May I contribute multiple times to this repo so I can create more awesome designs? I will be grateful if you allow me to do that.

**Comment by SooryaCodes** [comment]
> Hi @SooryaCodes May I contribute multiple times to this repo so I can create more awesome designs? I will be grateful if you allow me to do that.

Hey Adarsh, you can contribute multiple times. Glad to know that you are interested 😊.

**Comment by heyaadarsh** [comment]
> > Hi @SooryaCodes May I contribute multiple times to this repo so I can create more awesome designs? I will be grateful if you allow me to do that.
> 
> Hey Adarsh, you can contribute multiple times. Glad to know that you are interested 😊.

Thank you so much! Going to create more awesome designs!!

**Comment by SooryaCodes** [comment]
Do check it out contributions list. [Click here](https://sooryacodes.github.io/Hacktoberfest-2k22-Challenge/)

**Comment by heyaadarsh** [comment]
> > Hi @SooryaCodes May I contribute multiple times to this repo so I can create more awesome designs? I will be grateful if you allow me to do that.
> 
> Hey Adarsh, you can contribute multiple times. Glad to know that you are interested 😊.

Thanks, @SooryaCodes for allowing me to contribute multiple times. I created another pull request #35, please check it out and merge it into this wonderful design collection.
Thank You!

**Pull request merged**
